### ISSUE TITLE
Add tap to pypi

### ISSUE THREAD

**Issue by jtimeus-slalom** [dataops-tk/tap-powerbi-metadata#18]
use poetry and CICD to get automated builds to publish to pypi

**Comment by aaronsteers** [comment]
John - have you thought about the pattern you want to use for this?

If you like the pattern in the below Singer SDK MR, you could use almost the same code to implement it.

![image](https://user-images.githubusercontent.com/18150651/111811565-679fdf00-8894-11eb-9649-ab28c36a6324.png)


https://gitlab.com/meltano/singer-sdk/-/merge_requests/6

UPDATE: I realized that MR is huge. Here are the relevant lines:

https://gitlab.com/meltano/singer-sdk/-/blob/d0ae6da5fa8b4dd47dc0425648a72ddf1c3068ef/.gitlab-ci.yml#L31-43

```yaml
    - |
      echo "Publishing to PyPi..."
      if [[ "$BRANCH_NAME" == *main ]]
      then
        # Just print the version and don't change it
        poetry version --short
      else
        # Build a new version from the internal integer Job ID
        poetry version $(poetry version --short)-dev.$CI_JOB_ID
        poetry version --short
      fi
      echo -e "\nPublishing to version ref '$(poetry version --short)'...\n\n"
      # poetry config pypi-token.pypi "$PYPI_PUBLISH_TOKEN"
      poetry publish --build
```

The environment variables will be different on Github vs Gitlab, but there should be an equivalent for each.

**Comment by jtimeus-slalom** [comment]
Yes, I will definitely take advantage of your existing pattern.  I have created a pypi login and gotten a key.  I don't see the place to enter it in the Github, so I may need you to add additional privileges on this repo so I can add it as a variable for use in pipelines

**Comment by aaronsteers** [comment]
@jtimeus-slalom - I've made you `admin` on the repo. You should be able to add using the "New Repository Secret" option here:

https://github.com/dataops-tk/tap-powerbi-metadata/settings/secrets/actions
