### ISSUE TITLE
All properties are set to required

### ISSUE THREAD

**Issue by jtimeus-slalom** [dataops-tk/tap-powerbi-metadata#2]
Make Optional the default and only set Key properties to Required

**Comment by jtimeus-slalom** [comment]
workaround right now would be to manually type Optional=true to KeyProperties causing issues

**Comment by aaronsteers** [comment]
Fixed in SDK. ✅ 

As discussed, types now default to `required=False` - meaning the "optional" behavior is default unless otherwise specified.
