### ISSUE TITLE
key_properties in SCHEMA message is null when keys are defined in the Stream class

### ISSUE THREAD

**Issue by jtimeus-slalom** [dataops-tk/tap-powerbi-metadata#3]
class ActivityEventsStream(TapPowerBIMetadataStream):
    name = "ActivityEvents"
    path = "/admin/activityevents"
    primary_keys = ["Id"]
    replication_key = "CreationTime"
    schema = PropertiesList(
     ...

Results in
{
    "type": "SCHEMA",
     ...
    "key_properties": null
}

**Comment by aaronsteers** [comment]
Logged SDK issue here: https://gitlab.com/meltano/singer-sdk/-/issues/28

**Comment by aaronsteers** [comment]
Should be resolved now and I've updated this branch to the latest sdk version that contains the fix.

@jtimeus-slalom - Can you retest to confirm?

Thanks!

**Comment by jtimeus-slalom** [comment]
Looks good, output from `--discover` now shows Id in `key_properties`

```json
{
  "streams": [
    {
      "tap_stream_id": "ActivityEvents",
      "replication_key": "CreationTime",
      "replication_method": "INCREMENTAL",
      "key_properties": [
        "Id"
      ],
      "schema": {
        "properties": {
          "Id": {
            "type": [
              "string"
            ]
          },
          "RecordType": {
            "type": [
              "integer",
              "null"
            ]
          },
          "CreationTime": {
            "format": "date-time",
            "type": [
              "string"
            ]
          },
          "Operation": {
...          
```

**Comment by aaronsteers** [comment]
That's great! Thanks for confirming. 👍
