### ISSUE TITLE
Continuation Token not properly parsed

### ISSUE THREAD

**Issue by jtimeus-slalom** [dataops-tk/tap-powerbi-metadata#4]

**Comment by aaronsteers** [comment]
This has two parts:
 - ~~SDK Work: The type in the cookiecutter was incorrectly hinted as dict, when it should be of type `Response`. (Minor.)~~ (Fixed)
 - Tap Work: The code needs more work to properly handle the `continuationToken` contract. (Not blocked.)

**Comment by jtimeus-slalom** [comment]
Solved continuation token issue by treating with url_decode so that when was passed back in subsequent API call it was formed as expected by the endpoint
