### ISSUE TITLE
Unknown type 'None' for validator with schema

### ISSUE THREAD

**Issue by jtimeus-slalom** [dataops-tk/tap-powerbi-metadata#8]
jsonschema.exceptions.UnknownType:
Unknown type 'None' for validator with schema:

**Comment by aaronsteers** [comment]
@jtimeus-slalom - Thanks for logging this.

Should be fixed now via: https://gitlab.com/meltano/singer-sdk/-/commit/75946e669cbb9f4d98d7a8ab4d6f3295668be14d

Running `poetry add singer-sdk==0.0.2-dev.1064538345` within the repo should resolve.

**Comment by aaronsteers** [comment]
Sorry, please hold. Looks like the upload to pypi failed at the last moment.

Update:

Looks like a pypi outage:

https://downdetector.com/status/pypi/

![image](https://user-images.githubusercontent.com/18150651/109548983-2d57d480-7a82-11eb-9510-21e8318dc6a3.png)

**Comment by aaronsteers** [comment]
PyPi back online and the publish went through. New version ID is: `0.0.2-dev.1064772201`

I have gone ahead and imported the new version to this repo in my commit: fd85cada6c738b551a0f8784ab1fccf04aaf26bd

Executed: `poetry add singer-sdk==0.0.2-dev.1064772201` and added imports for `NumberType` (which were missing previously).

@jtimeus-slalom - If you can confirm the fix, this should be ready to close.

**Comment by jtimeus-slalom** [comment]
confirm fixed!

**Comment by aaronsteers** [comment]
Awesome - thanks! 🔥
